# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e847ec861540709eb94efbd393562df64be60dc8976f278b61d71232706e9357fc5f1f337bf0144e260bf4fe5bdabfc3136dd52109c6478b18445a19c4ce1ad

test:
  secret_key_base: 14d7b7951787408a898ead397a7f4e298d9254e0c46a768bbef8fea6216551e9abe0ce6eca39f8ffdd25034417e1c9cdd06267ef774b4e7c981d186819442be8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
